/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.test {
    export class Achievement_dialogUI extends Dialog {
		public contentSet:Laya.Sprite;
		public m_tap:Laya.Tab;
		public m_list:Laya.List;
		public Box:Laya.Box;
		public baseboard:Laya.Sprite;
		public blueBaseboard:Laya.Sprite;
		public reachButton:Laya.Button;
		public icon:Laya.Sprite;
		public rewardDiamond:Laya.Sprite;
		public describeLabel:Laya.Label;
		public diamondsNumber :Laya.FontClip;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/Achievement_dialog");
        }
    }
    REG("ui.test.Achievement_dialogUI",Achievement_dialogUI);
    export class CheckIn_dialogUI extends Dialog {
		public btn_oneReward:Laya.Button;
		public btn_twoReward:Laya.Button;
		public parentItem:Laya.Sprite;
		public btn_close:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/CheckIn_dialog");
        }
    }
    REG("ui.test.CheckIn_dialogUI",CheckIn_dialogUI);
    export class ExchangeDialogUI extends Dialog {
		public img_title:Laya.Image;
		public img_goldInfo:Laya.Image;
		public iconGold:Laya.Image;
		public icon_stone:Laya.Image;
		public btn_exchange:Laya.Button;
		public btn_add:Laya.Button;
		public btn_reduce:Laya.Button;
		public btn_close:Laya.Button;
		public btn_max:Laya.Button;
		public fc_consume:Laya.FontClip;
		public label_myHave:Laya.Label;
		public label_get:Laya.Label;
		public label_exchangeBate:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/ExchangeDialog");
        }
    }
    REG("ui.test.ExchangeDialogUI",ExchangeDialogUI);
    export class faceFighting_loadingSceneUI extends Scene {
		public view_sk:View;
		public sk:laya.ani.bone.Skeleton;
		public view_bar:View;
		public progressBar:Laya.Image;
		public progressBar_up:Laya.Image;
		public loadingLabel:Laya.FontClip;
		public sk_loading:laya.ani.bone.Skeleton;
		public img_touchStartGame:Laya.Image;
		public img_title:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/faceFighting_loadingScene");
        }
    }
    REG("ui.test.faceFighting_loadingSceneUI",faceFighting_loadingSceneUI);
    export class FacePlayingUI extends Scene {
		public startSence:Laya.FrameAnimation;
		public endSence:Laya.FrameAnimation;
		public WeaponStart:Laya.FrameAnimation;
		public WeaponEnd:Laya.FrameAnimation;
		public bg_03:Laya.Image;
		public bg_02:Laya.Image;
		public bg_01:Laya.Image;
		public Clouds:Laya.Sprite;
		public cloud_01:Laya.Image;
		public cloud_02:Laya.Image;
		public bulletParent_enemy:Laya.Sprite;
		public secondWeapon:Laya.Sprite;
		public leftSecondWeapon:Laya.Image;
		public shadow_left:Laya.Image;
		public rightSecondWeapon:Laya.Image;
		public shadow_right:Laya.Image;
		public pic_plane:Laya.Image;
		public shadow_main:Laya.Image;
		public dropBuffParent:Laya.Sprite;
		public effectParent:Laya.Sprite;
		public bulletParentUp_enmey:Laya.Sprite;
		public goldDrop:Laya.Sprite;
		public shopBtn:Laya.Button;
		public rankingBtn:Laya.Button;
		public shareBtn:Laya.Button;
		public checkInBtn:Laya.Button;
		public redDot_checkInBtn:Laya.Sprite;
		public achievementBtn:Laya.Button;
		public item0:Laya.Button;
		public item1:Laya.Button;
		public moneySprite:Laya.Sprite;
		public btn_exchangePower:Laya.Button;
		public fc_power:Laya.FontClip;
		public btn_exchangeGold:Laya.Button;
		public fc_gold:Laya.FontClip;
		public btn_exchangeDiamond:Laya.Button;
		public fc_diamond:Laya.FontClip;
		public img_mainGold:Laya.Sprite;
		public img_mainDiamond:Laya.Sprite;
		public img_mainPower:Laya.Sprite;
		public progressBarEnemyNum:Laya.ProgressBar;
		public progressLevel:Laya.Sprite;
		public HpLevel:Laya.Sprite;
		public hpBar2:Laya.Image;
		public hpMask2:Laya.Sprite;
		public hpBar:Laya.Image;
		public hpMask:Laya.Sprite;
		public label_score:Laya.FontClip;
		public label_distance:Laya.FontClip;
		public label_hpNum:Laya.Label;
		public lvscores_sprite:Laya.Sprite;
		public scoreMask:Laya.Sprite;
		public lv_max:Laya.Sprite;
		public lv_now:Laya.FontClip;
		public lv_scores:Laya.Label;
		public pauseBtn:Laya.Button;
		public img_progressPlane:Laya.Image;
		public haveEnemySprite:Laya.Sprite;
		public haveEnemy:Laya.FontClip;
		public progressLeftLabel:Laya.Label;
		public progressRightLabel:Laya.Label;
		public buffProgress:Laya.Sprite;
		public hurted_img:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/FacePlaying");
        }
    }
    REG("ui.test.FacePlayingUI",FacePlayingUI);
    export class GameFail_dialogUI extends Dialog {
		public ani1:Laya.FrameAnimation;
		public ani2:Laya.FrameAnimation;
		public bg_black:Laya.Image;
		public sprite_0:Laya.Sprite;
		public btn_revival:Laya.Button;
		public btn_settlement:Laya.Button;
		public label_enmeyDec:Laya.Label;
		public sk_settlement:laya.ani.bone.Skeleton;
		public sprite_1:Laya.Sprite;
		public oneGold:Laya.Label;
		public progress_sm:Laya.Image;
		public label_haveEnemy:Laya.Label;
		public progress_b:Laya.Image;
		public btn_rewardOne:Laya.Button;
		public btn_rewardTwo:Laya.Button;
		public nowLevel:Laya.Label;
		public label_distance:Laya.FontClip;
		public label_0:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/GameFail_dialog");
        }
    }
    REG("ui.test.GameFail_dialogUI",GameFail_dialogUI);
    export class GameFail_dialogbakUI extends Dialog {
		public bg_black:Laya.Sprite;
		public sk_settlement:laya.ani.bone.Skeleton;
		public btn_revival:Laya.Button;
		public labelNow:Laya.Label;
		public progressParent:Laya.Sprite;
		public failProgressbar:Laya.ProgressBar;
		public label_haveEnemy:Laya.Label;
		public btn_rewardOne:Laya.Button;
		public btn_rewardTwo:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/GameFail_dialogbak");
        }
    }
    REG("ui.test.GameFail_dialogbakUI",GameFail_dialogbakUI);
    export class LotteryUI extends Dialog {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/Lottery");
        }
    }
    REG("ui.test.LotteryUI",LotteryUI);
    export class obtainGoodsUI extends Dialog {
		public img_close:Laya.Image;
		public item0:Laya.Sprite;
		public num0:Laya.Label;
		public item1:Laya.Sprite;
		public num1:Laya.Sprite;
		public label_name:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/obtainGoods");
        }
    }
    REG("ui.test.obtainGoodsUI",obtainGoodsUI);
    export class obtainGoodsTenUI extends Dialog {
		public sprite_close:Laya.Sprite;
		public itemParent:Laya.Sprite;
		public fc_newNum:Laya.FontClip;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/obtainGoodsTen");
        }
    }
    REG("ui.test.obtainGoodsTenUI",obtainGoodsTenUI);
    export class popDialogUI extends Dialog {
		public showText:Laya.Label;
		public btn_cancel:Laya.Button;
		public btn_sure:Laya.Button;
		public btn_closeDialog:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/popDialog");
        }
    }
    REG("ui.test.popDialogUI",popDialogUI);
    export class RankingUI extends View {
		public btn_close:Laya.Button;
		public rankTab:Laya.Tab;
		public btn_level:Laya.Button;
		public btn_endless:Laya.Button;
		public openDataView:laya.ui.WXOpenDataViewer;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/Ranking");
        }
    }
    REG("ui.test.RankingUI",RankingUI);
    export class ReqLoadingUI extends Dialog {
		public blackSprite:Laya.Image;
		public loadIcon:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/ReqLoading");
        }
    }
    REG("ui.test.ReqLoadingUI",ReqLoadingUI);
    export class SetUI extends Dialog {
		public btn_close:Laya.Button;
		public btn_music:Laya.Button;
		public btn_sound:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/Set");
        }
    }
    REG("ui.test.SetUI",SetUI);
    export class Settlement_dialogUI extends Dialog {
		public ani1:Laya.FrameAnimation;
		public bg_black:Laya.Image;
		public sprite_0:Laya.Sprite;
		public sk3:laya.ani.bone.Skeleton;
		public sk_settlement:laya.ani.bone.Skeleton;
		public sk1:laya.ani.bone.Skeleton;
		public sprite_1:Laya.Sprite;
		public oneGold:Laya.Label;
		public progress_settlement:Laya.Image;
		public progress_bar:Laya.Image;
		public btn_rewardOne:Laya.Button;
		public btn_rewardTwo:Laya.Button;
		public nowLevel:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/Settlement_dialog");
        }
    }
    REG("ui.test.Settlement_dialogUI",Settlement_dialogUI);
    export class ShopDialogUI extends Dialog {
		public image_di:Laya.Image;
		public btn_close:Laya.Button;
		public btn_buyOne:Laya.Button;
		public fc_cosumeOne:Laya.FontClip;
		public btn_buyTen:Laya.Button;
		public fc_consumeTen:Laya.FontClip;
		public weapon_list:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/ShopDialog");
        }
    }
    REG("ui.test.ShopDialogUI",ShopDialogUI);
    export class skillsToChooseUI extends Dialog {
		public m_list:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/skillsToChoose");
        }
    }
    REG("ui.test.skillsToChooseUI",skillsToChooseUI);
    export class suspendInterfaceUI extends Dialog {
		public contentSet:Laya.Sprite;
		public m_list:Laya.List;
		public But_Quit:Laya.Button;
		public But_Continue:Laya.Button;
		public explain:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/suspendInterface");
        }
    }
    REG("ui.test.suspendInterfaceUI",suspendInterfaceUI);
}