/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Achievementreach from "./script/scene/Achievementreach"
import AchievementControl from "./script/scene/AchievementControl"
import closeTouchEffect from "./script/Tools/closeTouchEffect"
import CheckInControl from "./script/scene/CheckInControl"
import Exchange from "./script/scene/Exchange"
import LoadSceneControl from "./script/scene/LoadSceneControl"
import role from "./script/role/role"
import PlayingSceneControl from "./script/playing/PlayingSceneControl"
import ButtonTouchEffect from "./script/Effect/ButtonTouchEffect"
import AchievementButton from "./script/scene/AchievementButton"
import EquipUpdate from "./script/main/EquipUpdate"
import SettlementFailControl from "./script/scene/SettlementFailControl"
import RewardDialogControl from "./script/scene/RewardDialogControl"
import RewardTenControl from "./script/scene/RewardTenControl"
import PopDialogRunTime from "./script/scene/PopDialogRunTime"
import PopDialogControl from "./script/scene/PopDialogControl"
import RankingControl from "./script/scene/RankingControl"
import ReqLoadingControl from "./script/Effect/ReqLoadingControl"
import Setting from "./script/scene/Setting"
import SettlementControl from "./script/scene/SettlementControl"
import ShopControl from "./script/scene/ShopControl"
import EndlessChooseSkills from "./script/manage/EndlessChooseSkills"
import EndlessSuspend_explain from "./script/manage/EndlessSuspend_explain"
import ItemDetailControl from "./script/scene/ItemDetailControl"
import EndlessSuspend from "./script/manage/EndlessSuspend"
import GameUI from "./script/GameUI"
import GameControl from "./script/GameControl"
import BaoZha from "./script/role/BaoZha"
import Enemy from "./script/playing/Enemy"
import BossWarning from "./script/scene/BossWarning"
import BuffControl from "./script/playing/BuffControl"
import BuffProgressControl from "./script/role/BuffProgressControl"
import Bullet from "./script/Bullet"
import Bullet_face from "./script/playing/Bullet_face"
import Bullet_boss from "./script/playing/Bullet_boss"
import MuzzleControl from "./script/role/MuzzleControl"
import Bullet_second from "./script/role/Bullet_second"
import EnemySelfSkillControl from "./script/role/EnemySelfSkillControl"
import DropBox from "./script/DropBox"
import GoldDrop from "./script/role/GoldDrop"
import EndlessBuyItem from "./script/manage/EndlessBuyItem"
import movementLocus from "./script/role/movementLocus"
import HpaddEffectControl from "./script/Effect/HpaddEffectControl"
import toast from "./script/manage/toast"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="test/faceFighting_loadingScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/scene/Achievementreach.ts",Achievementreach);
        reg("script/scene/AchievementControl.ts",AchievementControl);
        reg("script/Tools/closeTouchEffect.ts",closeTouchEffect);
        reg("script/scene/CheckInControl.ts",CheckInControl);
        reg("script/scene/Exchange.ts",Exchange);
        reg("script/scene/LoadSceneControl.ts",LoadSceneControl);
        reg("script/role/role.ts",role);
        reg("script/playing/PlayingSceneControl.ts",PlayingSceneControl);
        reg("script/Effect/ButtonTouchEffect.ts",ButtonTouchEffect);
        reg("script/scene/AchievementButton.ts",AchievementButton);
        reg("script/main/EquipUpdate.ts",EquipUpdate);
        reg("script/scene/SettlementFailControl.ts",SettlementFailControl);
        reg("script/scene/RewardDialogControl.ts",RewardDialogControl);
        reg("script/scene/RewardTenControl.ts",RewardTenControl);
        reg("script/scene/PopDialogRunTime.ts",PopDialogRunTime);
        reg("script/scene/PopDialogControl.ts",PopDialogControl);
        reg("script/scene/RankingControl.ts",RankingControl);
        reg("script/Effect/ReqLoadingControl.ts",ReqLoadingControl);
        reg("script/scene/Setting.ts",Setting);
        reg("script/scene/SettlementControl.ts",SettlementControl);
        reg("script/scene/ShopControl.ts",ShopControl);
        reg("script/manage/EndlessChooseSkills.ts",EndlessChooseSkills);
        reg("script/manage/EndlessSuspend_explain.ts",EndlessSuspend_explain);
        reg("script/scene/ItemDetailControl.ts",ItemDetailControl);
        reg("script/manage/EndlessSuspend.ts",EndlessSuspend);
        reg("script/GameUI.ts",GameUI);
        reg("script/GameControl.ts",GameControl);
        reg("script/role/BaoZha.ts",BaoZha);
        reg("script/playing/Enemy.ts",Enemy);
        reg("script/scene/BossWarning.ts",BossWarning);
        reg("script/playing/BuffControl.ts",BuffControl);
        reg("script/role/BuffProgressControl.ts",BuffProgressControl);
        reg("script/Bullet.ts",Bullet);
        reg("script/playing/Bullet_face.ts",Bullet_face);
        reg("script/playing/Bullet_boss.ts",Bullet_boss);
        reg("script/role/MuzzleControl.ts",MuzzleControl);
        reg("script/role/Bullet_second.ts",Bullet_second);
        reg("script/role/EnemySelfSkillControl.ts",EnemySelfSkillControl);
        reg("script/DropBox.ts",DropBox);
        reg("script/role/GoldDrop.ts",GoldDrop);
        reg("script/manage/EndlessBuyItem.ts",EndlessBuyItem);
        reg("script/role/movementLocus.ts",movementLocus);
        reg("script/Effect/HpaddEffectControl.ts",HpaddEffectControl);
        reg("script/manage/toast.ts",toast);
    }
}
GameConfig.init();